# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA autora-experimentalist-example
repo_url: 'https://github.com/MoAljam/autora-experimentalist-challenge-g-1'

nav:
- Home: 'index.md'
- Quickstart: 'quickstart.md'
- Examples:
  - Basic Usage: 'Basic Usage.ipynb'
  - Additional Example: 'Additional Example.ipynb'
